version: '3.8'
services:
  neo4j:
    image: neo4j:5.15
    container_name: neo4j-lab4
    ports:
      - "7474:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=neo4j/laborator4
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
    volumes:
      - ./data:/data
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
